name: Build iMaqueiro APK

on: 
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22' # <-- A MÁGICA ESTÁ AQUI: Atualizamos para a versão 22!
          
      - name: Install Capacitor
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android @capacitor/push-notifications
          npx cap init "iMaqueiro Pro" br.com.imaqueiro.pro --web-dir .
          npx cap add android
          npx cap sync
          
      - name: Build Android APK
        run: |
          cd android && ./gradlew assembleDebug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: imaqueiro-pro-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
